// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('fields are not filled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('fields are not filled', async function() {
    await driver.get("https://school.moodledemo.net/course/view.php?id=51")
    await driver.manage().window().setRect({ width: 858, height: 816 })
    await driver.findElement(By.css("#module-944 .aalink")).click()
    await driver.findElement(By.css("#p429 .link > a")).click()
    await driver.findElement(By.linkText("Reply")).click()
    await driver.executeScript("window.scrollTo(0,200)")
    await driver.findElement(By.css(".btn-primary:nth-child(1) > span:nth-child(1)")).click()
  })
})
