// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Forum basic flow', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Forum basic flow', async function() {
    await driver.get("https://school.moodledemo.net/course/view.php?id=6")
    await driver.manage().window().setRect({ width: 856, height: 816 })
    await driver.findElement(By.linkText("World Cinema Forum")).click()
    await driver.findElement(By.linkText("Recent world cinema favourites")).click()
    await driver.findElement(By.linkText("Reply")).click()
    {
      const element = await driver.findElement(By.linkText("Permalink"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.name("post")).sendKeys("test reply")
    await driver.findElement(By.css(".btn-primary:nth-child(1) > span:nth-child(1)")).click()
    await driver.executeScript("window.scrollTo(0,100.80000305175781)")
  })
})

describe('Add more on a reply', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Add more on a reply', async function() {
    await driver.get("https://school.moodledemo.net/course/view.php?id=6")
    await driver.manage().window().setRect({ width: 854, height: 816 })
    {
      const element = await driver.findElement(By.linkText("World Cinema Forum"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("World Cinema Forum")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,4)")
    await driver.findElement(By.linkText("Recent world cinema favourites")).click()
    await driver.findElement(By.css("#p468 .btn:nth-child(5)")).click()
    await driver.executeScript("window.scrollTo(0,248)")
    await driver.findElement(By.name("post")).sendKeys("More on reply")
    await driver.findElement(By.css(".btn-primary:nth-child(1) > span:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.css("#yui_3_18_1_1_1701883113580_93 .icon"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,564.7999877929688)")
  })
})


describe('Choose wrong topic', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Choose wrong topic', async function() {
    await driver.get("https://school.moodledemo.net/course/view.php?id=51")
    await driver.manage().window().setRect({ width: 856, height: 816 })
    await driver.findElement(By.css("#module-944 .aalink")).click()
    await driver.findElement(By.linkText("Discuss this topic")).click()
    await driver.findElement(By.css(".discussion-nav:nth-child(4) .btn")).click()
    await driver.findElement(By.linkText("Reply")).click()
    await driver.executeScript("window.scrollTo(0,244)")
    await driver.findElement(By.name("post")).sendKeys("test")
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    await driver.findElement(By.id("single_select6570b0506fecc8")).click()
    await driver.findElement(By.css(".discussion-nav:nth-child(1)")).click()
  })
})


describe('Does not want to reply any more', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Does not want to reply any more', async function() {
    await driver.get("https://school.moodledemo.net/course/view.php?id=51")
    await driver.manage().window().setRect({ width: 854, height: 816 })
    await driver.findElement(By.css("#module-944 .aalink")).click()
    await driver.findElement(By.css("#p429 .link > a")).click()
    await driver.findElement(By.linkText("Reply")).click()
    await driver.executeScript("window.scrollTo(0,300)")
    await driver.findElement(By.name("post")).sendKeys("test cancel")
    await driver.findElement(By.name("cancelbtn")).click()
  })
})


describe('fields are not filled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('fields are not filled', async function() {
    await driver.get("https://school.moodledemo.net/course/view.php?id=51")
    await driver.manage().window().setRect({ width: 858, height: 816 })
    await driver.findElement(By.css("#module-944 .aalink")).click()
    await driver.findElement(By.css("#p429 .link > a")).click()
    await driver.findElement(By.linkText("Reply")).click()
    await driver.executeScript("window.scrollTo(0,200)")
    await driver.findElement(By.css(".btn-primary:nth-child(1) > span:nth-child(1)")).click()
  })
})



